bundler_args: ""
script: "bundle exec rake spec"
sudo: false
rvm:
  - 2.3.7
  - 2.4.5
  - 2.5.3
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails52.gemfile
branches:
  only: master
maxtrix:
  include:
    - rvm: 2.3.7
      script: bundle exec rubocop
