script: "bundle exec rake spec"
sudo: false
rvm:
  - 2.4
  - 2.5
  - 2.6
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails52.gemfile
branches:
  only: master
maxtrix:
  include:
    - name: Rubocop
      rvm: 2.4 # keep in sync with oldest ruby
      script: bundle exec rubocop
    - name: Benchmark
      rvm: 2.6 # keep in sync with newest ruby
      script: gem i gettext && gem i activesupport && bundle exec rake benchmark
    - name: Namespaces
      rvm: 2.6 # keep in sync with newest ruby
      script:
        - echo 'gem "gettext"' >> $BUNDLE_GEMFILE
        - echo 'gem "iconv"' >> $BUNDLE_GEMFILE
        - bundle install --no-deployment && bundle exec rake namespaces
